<a href="https://colab.research.google.com/github/GowthamiVudatta1530/Gowthami/blob/DAY-1/Day-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install opendatasets

Collecting opendatasets
  Downloading opendatasets-0.1.22-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from opendatasets) (4.66.6)
Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (from opendatasets) (1.6.17)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from opendatasets) (8.1.7)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2024.8.30)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.32.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (2.2.3)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle->opendatasets) (6.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle->opendatasets) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle->opendatasets) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle->opendatasets) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle->opendatasets) (3.10)
Downloading opendatasets-0.1.22-py3-none-any.whl (15 kB)
Installing collected packages: opendatasets
Successfully installed opendatasets-0.1.22

In [2]:
od.download("https://www.kaggle.com/datasets/valakhorasani/bank-transaction-dataset-for-fraud-detection")

NameError: name 'od' is not defined

In [3]:
od.download("https://www.kaggle.com/datasets/valakhorasani/bank-transaction-dataset-for-fraud-detection")

NameError: name 'od' is not defined

In [4]:
import opendatasets as od
od.download("https://www.kaggle.com/datasets/valakhorasani/bank-transaction-dataset-for-fraud-detection")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: gowthamivudatta
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/valakhorasani/bank-transaction-dataset-for-fraud-detection
Downloading bank-transaction-dataset-for-fraud-detection.zip to ./bank-transaction-dataset-for-fraud-detection

100%|██████████| 102k/102k [00:00<00:00, 21.1MB/s]

In [5]:
import pandas as pd
data = pd.read_csv('/content/bank-transaction-dataset-for-fraud-detection/bank_transactions_data_2.csv')

In [6]:
data.head()

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,PreviousTransactionDate
0,TX000001,AC00128,14.09,2023-04-11 16:29:14,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21,2024-11-04 08:08:08
1,TX000002,AC00455,376.24,2023-06-27 16:44:19,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91,2024-11-04 08:09:35
2,TX000003,AC00019,126.29,2023-07-10 18:16:08,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35,2024-11-04 08:07:04
3,TX000004,AC00070,184.50,2023-05-05 16:32:11,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06,2024-11-04 08:09:06
4,TX000005,AC00411,13.45,2023-10-16 17:51:24,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40,2024-11-04 08:06:39

In [7]:
# prompt: Using dataframe data: i need code for skewness, mean , median,mode,variatio

import pandas as pd
# Assuming your dataframe is named 'data'

# Calculate skewness for numerical columns
skewness_transaction_amount = data['TransactionAmount'].skew()
skewness_customer_age = data['CustomerAge'].skew()
skewness_transaction_duration = data['TransactionDuration'].skew()
skewness_login_attempts = data['LoginAttempts'].skew()
skewness_account_balance = data['AccountBalance'].skew()


print(f"Skewness of TransactionAmount: {skewness_transaction_amount}")
print(f"Skewness of CustomerAge: {skewness_customer_age}")
print(f"Skewness of TransactionDuration: {skewness_transaction_duration}")
print(f"Skewness of LoginAttempts: {skewness_login_attempts}")
print(f"Skewness of AccountBalance: {skewness_account_balance}")

# Calculate mean, median, and mode for numerical columns
def describe_column(column):
    print(f"\nColumn: {column.name}")
    print(f"Mean: {column.mean()}")
    print(f"Median: {column.median()}")
    print(f"Mode: {column.mode()[0]}") # Access the first mode value
    print(f"Variation: {column.var()}")
    # Standard deviation
    print(f"Standard Deviation: {column.std()}")

describe_column(data["TransactionAmount"])
describe_column(data["CustomerAge"])
describe_column(data["TransactionDuration"])
describe_column(data["LoginAttempts"])
describe_column(data["AccountBalance"])

Skewness of TransactionAmount: 1.7401067216605806
Skewness of CustomerAge: 0.14786438083389342
Skewness of TransactionDuration: 0.5994318037221608
Skewness of LoginAttempts: 5.173490517174514
Skewness of AccountBalance: 0.6012012313034707

Column: TransactionAmount
Mean: 297.5937778662421
Median: 211.14
Mode: 11.46
Variation: 85232.60902510892
Standard Deviation: 291.9462433824229

Column: CustomerAge
Mean: 44.673964968152866
Median: 45.0
Mode: 27
Variation: 316.5623167299538
Standard Deviation: 17.792198198366435

Column: TransactionDuration
Mean: 119.64331210191082
Median: 112.5
Mode: 63
Variation: 4894.927283012075
Standard Deviation: 69.96375692465404

Column: LoginAttempts
Mean: 1.1246019108280254
Median: 1.0
Mode: 1
Variation: 0.36320175305092295
Standard Deviation: 0.6026622213569746

Column: AccountBalance
Mean: 5114.302965764331
Median: 4735.51
Mode: 1400.04
Variation: 15217352.378406439
Standard Deviation: 3900.9424987311